### ISSUE TITLE
Using the card graphics symbols

### ISSUE THREAD

**Issue by jessehager** [masneyb/boot2sol#1]
As a possible enhancement, you could use something like:

```
family_symbols db 5, 6, 4, 3
```

to get the card symbols (♣♠♦♥) instead of letters.

**Comment by masneyb** [comment]
Thanks. I tried something like this previously:

`family_symbols db 0x06d,0x05d,0x04d,0x03d`

The issue was I shouldn't have put 0x in front of the initial number.

Thanks,

Brian
